# Generated by Django 6.0.6 on 2026-07-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='currency',
            name='unique_default_currency',
        ),
        migrations.RemoveConstraint(
            model_name='duration',
            name='unique_default_duration',
        ),
        migrations.RemoveConstraint(
            model_name='language',
            name='unique_default_language',
        ),
        migrations.AddField(
            model_name='currency',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='System'),
        ),
        migrations.AddField(
            model_name='duration',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='System'),
        ),
        migrations.AddField(
            model_name='language',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='System'),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='duration_affects_price',
            field=models.BooleanField(default=True, help_text='If enabled, duration is part of the price key: <br>45 and 60 min are priced differently. If disabled, price does not depend on duration.', verbose_name='Duration Affects Price'),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('is_system',), name='unique_default_currency'),
        ),
        migrations.AddConstraint(
            model_name='duration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('is_system',), name='unique_default_duration'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('is_system',), name='unique_default_language'),
        ),
        migrations.RemoveField(
            model_name='currency',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='duration',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='language',
            name='is_default',
        ),
    ]
