# Generated by Django 6.0.6 on 2026-07-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0002_remove_currency_unique_default_currency_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='currency',
            name='unique_default_currency',
        ),
        migrations.RemoveConstraint(
            model_name='duration',
            name='unique_default_duration',
        ),
        migrations.RemoveConstraint(
            model_name='language',
            name='unique_default_language',
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('is_system',), name='unique_system_currency'),
        ),
        migrations.AddConstraint(
            model_name='duration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('is_system',), name='unique_system_duration'),
        ),
        migrations.AddConstraint(
            model_name='language',
            constraint=models.UniqueConstraint(condition=models.Q(('is_system', True)), fields=('is_system',), name='unique_system_language'),
        ),
    ]
