# Generated by Django 6.0.6 on 2026-07-09 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0003_remove_currency_unique_default_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Rate')),
                ('date', models.DateField(verbose_name='Date')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='school_settings.currency', verbose_name='Currency')),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
                'ordering': ('-date', 'currency__code'),
                'constraints': [models.UniqueConstraint(fields=('currency', 'date'), name='unique_rate_per_currency_per_date')],
            },
        ),
    ]
