# Generated by Django 6.0.6 on 2026-07-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0004_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessontype',
            name='max_participants',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Leave blank for "Individual" lesson type', null=True, verbose_name='Max. Participants'),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='min_participants',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Leave blank for "Individual" lesson type', null=True, verbose_name='Min. Participants'),
        ),
    ]
