# Generated by Django 6.0.6 on 2026-07-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0005_alter_lessontype_max_participants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Sort Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Teacher Grade',
                'verbose_name_plural': 'Teacher Grades',
                'ordering': ('sort_order',),
            },
        ),
    ]
