# Generated by Django 6.0.6 on 2026-07-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0006_teachergrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='Symbol'),
            preserve_default=False,
        ),
    ]
