# Generated by Django 6.0.6 on 2026-07-17 19:36

from django.db import migrations


def seed_currencies(apps, schema_editor):
    Currency = apps.get_model("school_settings", "Currency")
    currencies = [
        ("EUR", "Euro",             "€", False),
        ("UAH", "Ukrainian Hryvna", "₴", True),
        ("USD", "US Dollar",        "$", False),
    ]
    for code, name, symbol, is_system in currencies:
        Currency.objects.update_or_create(
            code=code,
            defaults={"name": name, "symbol": symbol,
                      "is_system": is_system, "is_active": True},
        )

def seed_durations(apps, schema_editor):
    Duration = apps.get_model("school_settings", "Duration")
    durations = [
        (20, False),
        (30, False),
        (40, False),
        (45, False),
        (60, True),
        (75, False),
        (90, False),
        (120, False),
    ]
    for minutes, is_system in durations:
        Duration.objects.update_or_create(
            minutes=minutes,
            defaults={"is_system": is_system, "is_active": True},
        )

def seed_languages(apps, schema_editor):
    Language = apps.get_model("school_settings", "Language")
    languages = [
        ('English', True),
    ]
    for name, is_system in languages:
        Language.objects.update_or_create(
            name=name,
            defaults={"is_system": is_system, "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('school_settings', '0007_alter_currency_symbol'),
    ]

    operations = [
        migrations.RunPython(seed_currencies, migrations.RunPython.noop),
        migrations.RunPython(seed_durations, migrations.RunPython.noop),
        migrations.RunPython(seed_languages, migrations.RunPython.noop),
    ]
