# Generated by Django 6.0.6 on 2026-07-26 15:20

from django.db import migrations


def seed_lesson_types(apps, schema_editor):
    LessonType = apps.get_model("school_settings", "LessonType")
    types = [
        ('Personal', None, None, True),
        ('Small Group', 2, 6, True),
        ('Speaking Club', 5, 30, False),
    ]
    for name, min_participants, max_participants, duration_affects_price in types:
        LessonType.objects.update_or_create(
            name=name,
            min_participants=min_participants,
            max_participants=max_participants,
            duration_affects_price=duration_affects_price,
            defaults={"is_active": True},
        )


def seed_teacher_grade(apps, schema_editor):
    TeacherGrade = apps.get_model("school_settings", "TeacherGrade")
    grades = [
        ('Default', 0),
    ]
    for name, sort_order in grades:
        TeacherGrade.objects.update_or_create(
            name=name,
            sort_order=sort_order,
            defaults={"is_active": True},
        )


class Migration(migrations.Migration):
    dependencies = [
        ('school_settings', '0008_seed_system_school_settings'),
    ]

    operations = [
        migrations.RunPython(seed_lesson_types, migrations.RunPython.noop),
        migrations.RunPython(seed_teacher_grade, migrations.RunPython.noop),
    ]
