# Generated by Django 6.0.6 on 2026-06-30 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_teacherprofile_experience_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
