# Generated by Django 6.0.6 on 2026-07-15 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('school_settings', '0006_teachergrade'),
        ('users', '0003_studentprofile_is_active_studentprofile_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher_profile', to='finance.account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_settings.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='school_settings.teachergrade', verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='languages',
            field=models.ManyToManyField(to='school_settings.language', verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='lesson_types',
            field=models.ManyToManyField(to='school_settings.lessontype', verbose_name='Lesson Type'),
        ),
    ]
