# Generated by Django 6.0.6 on 2026-07-15 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('finance', '0001_initial'),
        ('pricing', '0003_remove_teacherrate_unique_pricing_teacherrate_key_and_more'),
        ('school_settings', '0006_teachergrade'),
        ('users', '0004_teacherprofile_account_teacherprofile_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to='finance.account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='companies.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_settings.currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='languages',
            field=models.ManyToManyField(to='school_settings.language', verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='personal_plan',
            field=models.ForeignKey(blank=True, help_text='The personal plan for this User. If User price must be different from the school plan.', null=True, on_delete=django.db.models.deletion.PROTECT, to='pricing.personalplan', verbose_name='Personal Plan'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='users.teacherprofile'),
        ),
    ]
