# Generated by Django 6.0.6 on 2026-07-17 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_studentprofile_account_studentprofile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='meeting_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='Meeting URL'),
        ),
    ]
