# Generated by Django 6.0.6 on 2026-07-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_personalplanrow_remove_personalplan_amount_and_more'),
        ('users', '0006_studentprofile_meeting_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='personal_plan',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='personal_plans',
            field=models.ManyToManyField(blank=True, help_text='The personal plan for this User. If User price must be different from the school plan.', to='pricing.personalplan', verbose_name='Personal Plan'),
        ),
    ]
