# Generated by Django 6.0.6 on 2026-09-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_studentprofile_personal_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='teacher',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='teacher',
            field=models.ManyToManyField(related_name='student_profiles', to='users.teacherprofile', verbose_name='Teacher'),
        ),
    ]
