# Generated by Django 6.0.6 on 2026-09-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_studentprofile_teacher_studentprofile_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='teacher',
            field=models.ManyToManyField(related_name='students', to='users.teacherprofile', verbose_name='Teacher'),
        ),
    ]
