# Generated by Django 6.0.6 on 2026-07-17 19:26

from django.db import migrations

def seed_types(apps, schema_editor):
    TransactionType = apps.get_model("finance", "TransactionType")
    types = [
        ("lesson_charge",    "Lesson charge",    "expense"),
        ("lesson_refund",    "Lesson refund",    "income"),
        ("teacher_refund",   "Teacher refund",   "expense"),
        ("teacher_accrual",  "Teacher accrual",  "income"),
        ("manual_payout",    "Manual payout",    "expense"),
        ("manual_topup",     "Manual top-up",    "income"),
        ("correction_out",   "Correction −",     "expense"),
        ("correction_in",    "Correction +",     "income"),
    ]
    for code, name, direction in types:
        TransactionType.objects.update_or_create(
            code=code,
            defaults={"name": name, "direction": direction,
                      "is_system": True, "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_transactiontype_transaction'),
    ]

    operations = [
        migrations.RunPython(seed_types, migrations.RunPython.noop)
    ]
