# Generated by Django 6.0.6 on 2026-07-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_seed_system_transaction_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('lesson_charge', 'Lesson charge'), ('lesson_refund', 'Lesson refund'), ('teacher_refund', 'Teacher refund'), ('teacher_accrual', 'Teacher accrual'), ('manual_payout', 'Manual payout'), ('manual_topup', 'Manual top-up'), ('correction_out', 'Correction −'), ('correction_in', 'Correction +')], max_length=15, verbose_name='Transaction Type'),
        ),
        migrations.DeleteModel(
            name='TransactionType',
        ),
    ]
