# Generated by Django 6.0.6 on 2026-07-12 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_settings', '0004_exchangerate'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_settings.currency', verbose_name='Currency')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_settings.language', verbose_name='Language')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_settings.lessontype', verbose_name='Lesson Type')),
            ],
            options={
                'verbose_name': 'School Price',
                'verbose_name_plural': 'School Prices',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolPriceRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_settings.duration', verbose_name='Duration')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='pricing.schoolprice', verbose_name='School Price')),
            ],
            options={
                'verbose_name': 'School Price Row',
                'verbose_name_plural': 'School Price Rows',
                'ordering': ['plan', 'duration__minutes'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_settings.currency', verbose_name='Currency')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_settings.language', verbose_name='Language')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_settings.lessontype', verbose_name='Lesson Type')),
            ],
            options={
                'verbose_name': 'Teacher Rate',
                'verbose_name_plural': 'Teacher Rates',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherRateRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_settings.duration', verbose_name='Duration')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='pricing.teacherrate', verbose_name='Teacher Rate')),
            ],
            options={
                'verbose_name': 'Teacher Rate Row',
                'verbose_name_plural': 'Teacher Rate Rows',
                'ordering': ['plan', 'duration__minutes'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='schoolprice',
            constraint=models.UniqueConstraint(fields=('currency', 'language', 'lesson_type'), name='unique_pricing_schoolprice_key'),
        ),
        migrations.AddConstraint(
            model_name='schoolpricerow',
            constraint=models.UniqueConstraint(fields=('plan', 'duration'), name='unique_duration_per_pricing_schoolpricerow'),
        ),
        migrations.AddConstraint(
            model_name='teacherrate',
            constraint=models.UniqueConstraint(fields=('currency', 'language', 'lesson_type'), name='unique_pricing_teacherrate_key'),
        ),
        migrations.AddConstraint(
            model_name='teacherraterow',
            constraint=models.UniqueConstraint(fields=('plan', 'duration'), name='unique_duration_per_pricing_teacherraterow'),
        ),
    ]
