# Generated by Django 6.0.6 on 2026-07-12 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
        ('school_settings', '0005_alter_lessontype_max_participants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_settings.currency', verbose_name='Currency')),
                ('duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_settings.duration', verbose_name='Duration')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_settings.language', verbose_name='Language')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_settings.lessontype', verbose_name='Lesson Type')),
            ],
            options={
                'verbose_name': 'Personal Plan',
                'verbose_name_plural': 'Personal Plans',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
