# Generated by Django 6.0.6 on 2026-07-15 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_personalplan'),
        ('school_settings', '0006_teachergrade'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='teacherrate',
            name='unique_pricing_teacherrate_key',
        ),
        migrations.AddField(
            model_name='teacherrate',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='school_settings.teachergrade', verbose_name='Grade'),
        ),
        migrations.AddConstraint(
            model_name='teacherrate',
            constraint=models.UniqueConstraint(fields=('grade', 'currency', 'language', 'lesson_type'), name='unique_teachers_rates_key'),
        ),
    ]
