# Generated by Django 6.0.6 on 2026-07-25 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_remove_teacherrate_unique_pricing_teacherrate_key_and_more'),
        ('school_settings', '0008_seed_system_school_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalPlanRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Personal Plan Row',
                'verbose_name_plural': 'Personal Plan Rows',
                'ordering': ['plan', 'duration__minutes'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='personalplan',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='personalplan',
            name='duration',
        ),
        migrations.AddConstraint(
            model_name='personalplan',
            constraint=models.UniqueConstraint(fields=('currency', 'language', 'lesson_type'), name='unique_pricing_personalplan_key'),
        ),
        migrations.AddField(
            model_name='personalplanrow',
            name='duration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_settings.duration', verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='personalplanrow',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='pricing.personalplan', verbose_name='Personal Plan'),
        ),
        migrations.AddConstraint(
            model_name='personalplanrow',
            constraint=models.UniqueConstraint(fields=('plan', 'duration'), name='unique_duration_per_pricing_personalplanrow'),
        ),
    ]
