# Generated by Django 6.0.6 on 2026-07-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0004_personalplanrow_remove_personalplan_amount_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='personalplan',
            name='unique_pricing_personalplan_key',
        ),
    ]
