# Generated by Django 6.0.6 on 2026-07-14 19:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('pricing', '0002_personalplan'),
        ('school_settings', '0005_alter_lessontype_max_participants_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('coverage_percent', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Coverage percent')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='finance.account', verbose_name='Account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_settings.currency', verbose_name='Currency')),
                ('personal_plan', models.ForeignKey(blank=True, help_text='The personal plan for this company. If company price must be different from the school plan.', null=True, on_delete=django.db.models.deletion.PROTECT, to='pricing.personalplan', verbose_name='Personal Plan')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
