# Generated by Django 6.0.6 on 2026-07-17 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('pricing', '0003_remove_teacherrate_unique_pricing_teacherrate_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='personal_plan',
            field=models.ForeignKey(blank=True, help_text='The personal plan for this company.If company price must be different from the school plan.', null=True, on_delete=django.db.models.deletion.PROTECT, to='pricing.personalplan', verbose_name='Personal Plan'),
        ),
    ]
