# Generated by Django 6.0.6 on 2026-07-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_personal_plan'),
        ('pricing', '0004_personalplanrow_remove_personalplan_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='personal_plan',
        ),
        migrations.AddField(
            model_name='company',
            name='personal_plans',
            field=models.ManyToManyField(blank=True, help_text='The personal plan for this company.If company price must be different from the school plan.', to='pricing.personalplan', verbose_name='Personal Plan'),
        ),
    ]
