# Generated by Django 6.0.6 on 2026-07-17 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_settings', '0007_alter_currency_symbol'),
        ('users', '0006_studentprofile_meeting_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('conducted', 'Conducted'), ('missed', 'Missed')], default='planned', max_length=10, verbose_name='Status')),
                ('start_at', models.DateTimeField(verbose_name='Start at')),
                ('meeting_url', models.URLField(blank=True, max_length=255, verbose_name='Meeting URL')),
                ('topic', models.CharField(max_length=255, verbose_name='Topic')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('homework', models.TextField(blank=True, verbose_name='Homework')),
                ('lesson_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lesson price')),
                ('duration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_settings.duration', verbose_name='Duration')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_settings.language', verbose_name='Language')),
                ('lesson_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school_settings.currency', verbose_name='Currency')),
                ('lesson_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='school_settings.lessontype', verbose_name='LessonType')),
                ('students', models.ManyToManyField(related_name='lessons', to='users.studentprofile', verbose_name='Students')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='users.teacherprofile', verbose_name='Teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
