# Generated by Django 6.0.6 on 2026-07-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ('-start_at',), 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
    ]
